// <auto-generated />
using System;
using AssessmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssessmentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331173743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssessmentService.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("AssessmentService.Models.AssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremiumResult")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("AssessmentService.Models.MCQQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Subtopic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MCQQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOption = "A",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "Many forms",
                            OptionB = "Hiding data",
                            OptionC = "Code reuse",
                            OptionD = "Creating objects",
                            OrderIndex = 1,
                            Subtopic = "OOP",
                            Text = "What is polymorphism in OOP?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOption = "B",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "public",
                            OptionB = "private",
                            OptionC = "protected",
                            OptionD = "internal",
                            OrderIndex = 2,
                            Subtopic = "OOP",
                            Text = "Which modifier restricts access to the containing class?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectOption = "A",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "async",
                            OptionB = "await",
                            OptionC = "Task",
                            OptionD = "Thread",
                            OrderIndex = 3,
                            Subtopic = "Async",
                            Text = "What keyword is used for asynchronous methods?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectOption = "B",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "Thread.Sleep()",
                            OptionB = "await Task.Delay()",
                            OptionC = "Wait()",
                            OptionD = "Yield()",
                            OrderIndex = 4,
                            Subtopic = "Async",
                            Text = "How to pause async method execution?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectOption = "C",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "ICollection",
                            OptionB = "IList",
                            OptionC = "IEnumerable",
                            OptionD = "IDictionary",
                            OrderIndex = 5,
                            Subtopic = "Collections",
                            Text = "Which interface allows iterating over a collection?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectOption = "C",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "List represents fixed size",
                            OptionB = "Array represents dynamic size",
                            OptionC = "List is dynamic, Array is fixed",
                            OptionD = "No difference",
                            OrderIndex = 6,
                            Subtopic = "Collections",
                            Text = "What is the key difference between Array and List?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectOption = "A",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "Language Integrated Query",
                            OptionB = "Language Internal Query",
                            OptionC = "List Integrated Query",
                            OptionD = "List Internal Query",
                            OrderIndex = 7,
                            Subtopic = "LINQ",
                            Text = "What does LINQ stand for?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectOption = "B",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "Select()",
                            OptionB = "Where()",
                            OptionC = "OrderBy()",
                            OptionD = "GroupBy()",
                            OrderIndex = 8,
                            Subtopic = "LINQ",
                            Text = "Which LINQ method filters elements?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectOption = "C",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "try",
                            OptionB = "catch",
                            OptionC = "finally",
                            OptionD = "throw",
                            OrderIndex = 9,
                            Subtopic = "ExceptionHandling",
                            Text = "Which block must execute regardless of exceptions?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectOption = "C",
                            Domain = "C#",
                            Marks = 1,
                            OptionA = "SystemException",
                            OptionB = "ApplicationException",
                            OptionC = "Exception",
                            OptionD = "Error",
                            OrderIndex = 10,
                            Subtopic = "ExceptionHandling",
                            Text = "What is the base class for all exceptions?"
                        });
                });

            modelBuilder.Entity("AssessmentService.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
